// Questions, dares, and drinking options
const questions = [
  "What is your most embarrassing moment?",
  "What is the biggest secret you've kept from your parents?",
  "What is your most embarrassing moment?",
  "What is the biggest secret you've kept from your parents?",
  "Who was your first crush?",
  "What's the worst date you've ever been on?",
  "Have you ever lied to get out of a bad situation?",
  "What's the most childish thing you still do?",
  "What's your biggest fear?",
  "Have you ever cheated on a test?",
  "What's the worst thing you've ever done?",
  "What's the most trouble you've ever gotten into?",
  "Who is your secret crush?",
  "What's the most embarrassing thing you've done for a friend?",
  "What's the weirdest thing you've ever eaten?",
  "Have you ever stolen something?",
  "What's the worst lie you've ever told?",
  "What's your guilty pleasure?",
  "What's the most embarrassing thing you've worn?",
  "What's the most awkward situation you've ever been in?",
  "Have you ever had a crush on someone here?",
  "What's the most awkward thing you've said to someone you liked?",
  "Have you ever been caught doing something you shouldn't have?",
  "What's the most embarrassing thing in your room?",
  "What's the grossest thing you've ever done?",
  "Have you ever been rejected?",
  "What's the most embarrassing thing you've done in public?",
  "Have you ever had a wardrobe malfunction?",
  "What's the most embarrassing thing you've searched for online?",
  "Have you ever had a crush on a friend's partner?",
  "What's the most embarrassing nickname you've had?",
  "What's the silliest thing you've ever done?",
  "What's the most embarrassing thing you've done for love?",
  "Have you ever had a crush on one of your teachers?",
  "What's the most embarrassing thing you've done at school?",
  "Have you ever been caught lying?",
  "What's the most embarrassing song you like?",
  "What's the most embarrassing thing you've done in front of your crush?",
  "What's your most embarrassing habit?",
  "Have you ever been caught picking your nose?",
  "What's the most embarrassing thing you've done on social media?",
  "Have you ever been caught talking to yourself?",
  "What's the most embarrassing thing you've done while drunk?",
  "Have you ever had a crush on a sibling's friend?",
  "What's the most embarrassing thing you've done on a dare?",
  "What's the most embarrassing thing you've done at a party?",
  "Have you ever been caught sneaking out?",
  "What's the weirdest dream you've ever had?",
  "What's the most embarrassing thing you've done in front of your parents?",
  "Have you ever been caught cheating?",
  "What's the most embarrassing thing you've done during a date?",
  "What's the most embarrassing thing you've done at work?",
  "What's the most embarrassing thing you've done in a relationship?",
  "Have you ever been caught eavesdropping?",
  "What's the most embarrassing thing you've done in a public restroom?",
  "Have you ever been caught spying on someone?",
  "What's the most embarrassing thing you've done at a family gathering?",
  "What's the most embarrassing thing you've done at a friend's house?",
  "What's the most embarrassing thing you've done in a car?",
  "What's the most embarrassing thing you've done at a restaurant?",
  "Have you ever been caught lying about your age?",
  "What's the most embarrassing thing you've done while shopping?",
  "What's the most embarrassing thing you've done at the gym?",
  "Have you ever been caught stealing?",
  "What's the most embarrassing thing you've done while cooking?",
  "What's the most embarrassing thing you've done at a wedding?",
  "What's the most embarrassing thing you've done at a funeral?",
  "What's the most embarrassing thing you've done at a concert?",
  "What's the most embarrassing thing you've done at a sports event?",
  "What's the most embarrassing thing you've done at a theme park?",
  "What's the most embarrassing thing you've done on vacation?",
  "What's the most embarrassing thing you've done at a hotel?",
  "What's the most embarrassing thing you've done on a plane?",
  "What's the most embarrassing thing you've done on a train?",
  "What's the most embarrassing thing you've done on a bus?",
  "What's the most embarrassing thing you've done in a taxi?",
  "What's the most embarrassing thing you've done while driving?",
  "What's the most embarrassing thing you've done while biking?",
  "What's the most embarrassing thing you've done while walking?",
  "What's the most embarrassing thing you've done while running?",
  "What's the most embarrassing thing you've done while swimming?",
  "What's the most embarrassing thing you've done while dancing?",
  "What's the most embarrassing thing you've done while singing?",
  "What's the most embarrassing thing you've done while playing an instrument?",
  "What's the most embarrassing thing you've done while acting?",
  "What's the most embarrassing thing you've done while painting?",
  "What's the most embarrassing thing you've done while drawing?",
  "What's the most embarrassing thing you've done while writing?",
  "What's the most embarrassing thing you've done while reading?",
  "What's the most embarrassing thing you've done while studying?",
  "What's the most embarrassing thing you've done while working?",
  "What's the most embarrassing thing you've done while exercising?",
  "What's the most embarrassing thing you've done while practicing a sport?",
  "What's the most embarrassing thing you've done while playing a game?",
  "What's the most embarrassing thing you've done while watching TV?",
  "What's the most embarrassing thing you've done while watching a movie?",
  "What's the most embarrassing thing you've done while listening to music?",
  "What's the most embarrassing thing you've done while taking a picture?",
  "What's the most embarrassing thing you've done while filming a video?",
  "What's the most embarrassing thing you've done while live streaming?",
  "What's the most embarrassing thing you've done while on a video call?",
  "What's the most embarrassing thing you've done while on a phone call?",
  "What's the most embarrassing thing you've done while texting?",
  "What's the most embarrassing thing you've done while emailing?",
  "What's the most embarrassing thing you've done while using social media?",
  "What's the most embarrassing thing you've done while online shopping?",
  "What's the most embarrassing thing you've done while browsing the internet?",
  "What's the most embarrassing thing you've done while playing an online game?",
  "What's the most embarrassing thing you've done while chatting online?",
  "What's the most embarrassing thing you've done while using a dating app?",
  "What's the most embarrassing thing you've done while at a party?",
  "What's the most embarrassing thing you've done while at a club?",
  "What's the most embarrassing thing you've done while at a bar?",
  "What's the most embarrassing thing you've done while at a beach?",
  "What's the most embarrassing thing you've done while at a pool?",
  "What's the most embarrassing thing you've done while at a sauna?",
  "What's the most embarrassing thing you've done while at a spa?",
  "What's the most embarrassing thing you've done while at a doctor's office?",
  "What's the most embarrassing thing you've done while at a dentist's office?",
  "What's the most embarrassing thing you've done while at a hospital?",
  "What's the most embarrassing thing you've done while at a pharmacy?",
  "What's the most embarrassing thing you've done while at a grocery store?",
  "What's the most embarrassing thing you've done while at a mall?",
  "What's the most embarrassing thing you've done while at a market?",
  "What's the most embarrassing thing you've done while at a library?",
  "What's the most embarrassing thing you've done while at a museum?",
  "What's the most embarrassing thing you've done while at a zoo?",
  "What's the most embarrassing thing you've done while at an aquarium?",
  "What's the most embarrassing thing you've done while at a park?",
  "What's the most embarrassing thing you've done while at a playground?",
  "What's the most embarrassing thing you've done while at a festival?",
  "What's the most embarrassing thing you've done while at a fair?",
  "What's the most embarrassing thing you've done while at a carnival?",
  "What's the most embarrassing thing you've done while at a parade?",
  "What's the most embarrassing thing you've done while at a rally?",
  "What's the most embarrassing thing you've done while at a protest?",
  "What's the most embarrassing thing you've done while at a funeral?",
  "What's the most embarrassing thing you've done while at a wedding?",
  "What's the most embarrassing thing you've done while at a birthday party?",
  "What's the most embarrassing thing you've done while at a graduation?",
  "What's the most embarrassing thing you've done while at a reunion?",
  "What's the most embarrassing thing you've done while at a sleepover?",
  "What's the most embarrassing thing you've done while at a slumber party?",
  "What's the most embarrassing thing you've done while at a movie night?",
  "What's the most embarrassing thing you've done while at a game night?",
  "What's the most embarrassing thing you've done while at a dinner party?",
  "What's the most embarrassing thing you've done while at a barbecue?",
  "What's the most embarrassing thing you've done while at a picnic?",
  "What's the most embarrassing thing you've done while at a camping trip?",
  "What's the most embarrassing thing you've done while at a road trip?",
  "What's the most embarrassing thing you've done while at a cruise?",
  "What's the most embarrassing thing you've done while at a resort?",
  "What's the most embarrassing thing you've done while at a hostel?",
  "What's the most embarrassing thing you've done while at a bed and breakfast?",
  "What's the most embarrassing thing you've done while at a friend's house?",
  "What's the most embarrassing thing you've done while at a relative's house?",
  "What's the most embarrassing thing you've done while at a neighbor's house?",
  "What's the most embarrassing thing you've done while at a stranger's house?",
  "What's the most embarrassing thing you've done while at a coworker's house?",
  "What's the most embarrassing thing you've done while at a boss's house?",
  "What's the most embarrassing thing you've done while at a classmate's house?",
  "What's the most embarrassing thing you've done while at a teammate's house?",
  "What's the most embarrassing thing you've done while at a coach's house?",
  "What's the most embarrassing thing you've done while at a mentor's house?",
  "What's the most embarrassing thing you've done while at a teacher's house?",
  "What's the most embarrassing thing you've done while at a tutor's house?",
  "What's the most embarrassing thing you've done while at a babysitter's house?",
  "What's the most embarrassing thing you've done while at a friend's parent's house?",
  "What's the most embarrassing thing you've done while at a friend's sibling's house?",
  "What's the most embarrassing thing you've done while at a friend's grandparent's house?",
  "What's the most embarrassing thing you've done while at a friend's cousin's house?",
  "What's the most embarrassing thing you've done while at a friend's aunt's house?",
  "What's the most embarrassing thing you've done while at a friend's uncle's house?"
];

const dares = [
  "Do a silly dance for 29 seconds.",
  "Sing a song chosen by the group.",
  "Do a silly dance for 30 seconds.",
  "Sing a song chosen by the group.",
  "Talk in an accent for the next 3 rounds.",
  "Let someone tickle you for 30 seconds.",
  "Do an impression of a celebrity until someone can guess who you are.",
  "Act like a chicken until your next turn.",
  "Speak in a robot voice until your next turn.",
  "Let the person to your left draw on your face with a pen.",
  "Talk in a high-pitched voice until your next turn.",
  "Do 10 pushups.",
  "Do 10 jumping jacks.",
  "Wear socks on your hands for the next 3 rounds.",
  "Let someone style your hair.",
  "Do your best impression of someone in the room and keep going until someone can guess who you are.",
  "Let the group pose you in an embarrassing position and take a picture.",
  "Make up a 30-second opera about a person or people in the group and perform it.",
  "Talk without closing your mouth.",
  "Let the person to your right redo your hairstyle.",
  "Post an embarrassing photo on social media.",
  "Let the person to your left text anyone from your phone.",
  "Let the group look through your phone for 2 minutes.",
  "Let someone write a word on your forehead in a permanent marker.",
  "Eat a raw onion slice.",
  "Let the person to your left draw a mustache on your face.",
  "Wear a funny hat for the next 3 rounds.",
  "Do your best chicken dance outside on the lawn.",
  "Make a face mask out of toilet paper and wear it for the next round.",
  "Let someone give you a wedgie.",
  "Let someone in the group give you a new hairstyle.",
  "Let someone write a word on your face with lipstick.",
  "Talk in a funny accent for the next 3 rounds.",
  "Do your best impression of a baby being born.",
  "Do your best impression of a cat for the next 3 rounds.",
  "Do your best impression of a dog for the next 3 rounds.",
  "Do your best impression of a monkey for the next 3 rounds.",
  "Do your best impression of a fish for the next 3 rounds.",
  "Do your best impression of a dinosaur for the next 3 rounds.",
  "Do your best impression of a person in the room until someone can guess who you are.",
  "Do your best impression of an animal until someone can guess what you are.",
  "Do your best impression of a celebrity until someone can guess who you are.",
  "Do your best impression of a cartoon character until someone can guess who you are.",
  "Do your best impression of a superhero until someone can guess who you are.",
  "Do your best impression of a villain until someone can guess who you are.",
  "Do your best impression of a famous singer until someone can guess who you are.",
  "Do your best impression of a famous actor until someone can guess who you are.",
  "Do your best impression of a famous politician until someone can guess who you are.",
  "Do your best impression of a famous athlete until someone can guess who you are.",
  "Do your best impression of a famous historical figure until someone can guess who you are.",
  "Do your best impression of a famous fictional character until someone can guess who you are.",
  "Do your best impression of a famous YouTuber until someone can guess who you are.",
  "Do your best impression of a famous TikToker until someone can guess who you are.",
  "Do your best impression of a famous Instagrammer until someone can guess who you are.",
  "Do your best impression of a famous Snapchat person until someone can guess who you are.",
  "Do your best impression of a famous LinkedIn person until someone can guess who you are.",
  "Do your best impression of a famous Facebook person until someone can guess who you are.",
  "Do your best impression of a famous Twitter person until someone can guess who you are.",
  "Do your best impression of a famous Pinterest person until someone can guess who you are.",
  "Do your best impression of a famous Reddit person until someone can guess who you are."
];

const drinks = [
  "Take a shot of vodka.",
  "Drink a glass of beer.",
  "Take a sip of a mixed drink.",
  "Finish your current drink.",
  "Finish your drink.",
  "Take two shots if you’ve ever cheated in a relationship.",
  "Take two shots if you’ve ever lied to a boss.",
  "Take two sips of your drink.",
  "Take a shot if you've ever skipped class.",
  "Take a shot if you've ever had a crush on a teacher.",
  "Take a shot if you've ever been on a blind date.",
  "Take a shot if you have a hidden talent.",
  "Take a shot if you’ve ever lied about your age.",
  "Take a shot if you’ve ever been caught sneaking out.",
  "Take a shot if you’ve ever had a crush on a friend’s sibling.",
  "Take a shot if you’ve ever cheated on a test.",
  "Take a shot if you’ve ever been on a sports team.",
  "Take a sip of your drink.",
  "Take a sip if you have a pet.",
  "Take a sip if you've ever been on a road trip.",
  "Take a sip if you’ve ever played a musical instrument.",
  "Take a sip if you've ever won a prize.",
  "Take a sip if you have a tattoo.",
  "Take a sip if you've ever flown in a plane.",
  "Take a sip if you've ever been to a concert.",
  "Take a sip if you've ever traveled outside your country.",
  "Take a sip if you've ever stayed up all night."
];

// Function to get a random element from an array
function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Event listeners for buttons
document.getElementById("startGame").addEventListener("click", () => {
  document.getElementById("messages").innerText =
    "Choose: Drink, Dare, or Question.";
});
"Do a silly dance for 30 seconds.",
  "Sing a song chosen by the group.",
  "Talk in an accent for the next 3 rounds.",
  "Let someone tickle you for 30 seconds.",
  "Do an impression of a celebrity until someone can guess who you are.",
  "Act like a chicken until your next turn.",
  "Speak in a robot voice until your next turn.",
  "Let the person to your left draw on your face with a pen.",
  "Talk in a high-pitched voice until your next turn.",
  "Do 10 pushups.",
  "Do 10 jumping jacks.",
  "Wear socks on your hands for the next 3 rounds.",
  "Let someone style your hair.",
  "Do your best impression of someone in the room and keep going until someone can guess who you are.",
  "Let the group pose you in an embarrassing position and take a picture.",
  "Make up a 30-second opera about a person or people in the group and perform it.",
  "Talk without closing your mouth.",
  "Let the person to your right redo your hairstyle.",
  "Post an embarrassing photo on social media.",
  "Let the person to your left text anyone from your phone.",
  "Let the group look through your phone for 2 minutes.",
  "Let someone write a word on your forehead in a permanent marker.",
  "Eat a raw onion slice.",
  "Let the person to your left draw a mustache on your face.",
  "Wear a funny hat for the next 3 rounds.",
  "Do your best chicken dance outside on the lawn.",
  "Make a face mask out of toilet paper and wear it for the next round.",
  "Let someone give you a wedgie.",
  "Let someone in the group give you a new hairstyle.",
  "Let someone write a word on your face with lipstick.",
  "Talk in a funny accent for the next 3 rounds.",
  "Do your best impression of a baby being born.",
  "Do your best impression of a cat for the next 3 rounds.",
  "Do your best impression of a dog for the next 3 rounds.",
  "Do your best impression of a monkey for the next 3 rounds.",
  "Do your best impression of a fish for the next 3 rounds.",
  "Do your best impression of a dinosaur for the next 3 rounds.",
  "Do your best impression of a person in the room until someone can guess who you are.",
  "Do your best impression of an animal until someone can guess what you are.",
  "Do your best impression of a celebrity until someone can guess who you are.",
  "Do your best impression of a cartoon character until someone can guess who you are.",
  "Do your best impression of a superhero until someone can guess who you are.",
  "Do your best impression of a villain until someone can guess who you are.",
  "Do your best impression of a famous singer until someone can guess who you are.",
  "Do your best impression of a famous actor until someone can guess who you are.",
  "Do your best impression of a famous politician until someone can guess who you are.",
  "Do your best impression of a famous athlete until someone can guess who you are.",
  "Do your best impression of a famous historical figure until someone can guess who you are.",
  "Do your best impression of a famous fictional character until someone can guess who you are.",
  "Do your best impression of a famous YouTuber until someone can guess who you are.",
  "Do your best impression of a famous TikToker until someone can guess who you are.",
  "Do your best impression of a famous Instagrammer until someone can guess who you are.",
  "Do your best impression of a famous Snapchat person until someone can guess who you are.",
  "Do your best impression of a famous LinkedIn person until someone can guess who you are.",
  "Do your best impression of a famous Facebook person until someone can guess who you are.",
  "Do your best impression of a famous Twitter person until someone can guess who you are.",
  "Do your best impression of a famous Pinterest person until someone can guess who you are.",
  "Do your best impression of a famous Reddit person until someone can guess who you are.",
  document.getElementById("drink").addEventListener("click", () => {
    const drink = getRandomElement(drinks);
    document.getElementById("messages").innerText = `Drink: ${drink}`;
  });

document.getElementById("dare").addEventListener("click", () => {
  const dare = getRandomElement(dares);
  document.getElementById("messages").innerText = `Dare: ${dare}`;
});

document.getElementById("question").addEventListener("click", () => {
  const question = getRandomElement(questions);
  document.getElementById("messages").innerText = `Question: ${question}`;
});
